#!/bin/bash

######################################
#   lotus compile test_libshmmedia
######################################
PRJ_PATH=$(shell pwd)/../..
SRC_PATH=$(shell pwd)
SUF_SRC=.cpp
DEP_1=$(PRJ_PATH)/../libshmmediaProto
DEP_2=$(PRJ_PATH)/../libvaItemSharedMemory
DEP_3=$(PRJ_PATH)/../libtvufourcc
CFLAGS+= -g -fPIC -DTVU_LINUX -I$(PRJ_PATH)/include -I$(DEP_1)/include -I$(DEP_3)/include 
LDFLAGS+= -L$(PRJ_PATH)/lib -L$(DEP_1)/lib -L$(DEP_2)/lib -L$(PRJ_PATH)/../libsharememory/lib -lshmmedia -lshmmediaProto -lsharememory -lvaItemSharedMemory -pthread -lrt 

#TVULIVE_TEST_ENABLE=asdf
DEP_4=$(PRJ_PATH)/../libtvulive

ifdef TVULIVE_TEST_ENABLE
    CFLAGS+=-I$(DEP_4)/include -D_TVULIVE_TEST_ENABLE
    LDFLAGS+=-L$(DEP_4)/lib -ltvulive
endif

TEST_SRCS=$(wildcard $(SRC_PATH)/*$(SUF_SRC))
TEST_OBJS=$(patsubst %$(SUF_SRC), %.o, $(TEST_SRCS))
TEST_EXE=test_shm_tvulive

all:$(TEST_EXE)
	@#echo $(TEST_OBJS)

$(TEST_OBJS):%.o:%$(SUF_SRC)
	$(CXX) -o $@ $(CFLAGS) -c $^

$(TEST_EXE):$(TEST_OBJS) $(LIB_AR_PRJ)
	$(CXX) -o $@ $< $(LDFLAGS)

clean:
	$(RM) $(TEST_OBJS) $(TEST_EXE)

install:
	@
uninstall:
	@

.PHONY:all clean install uninstall

