#!/bin/bash

######################################
#   lotus compile test_libshmmedia
######################################
PRJ_PATH=$(shell pwd)/../..
SRC_PATH=$(shell pwd)
SUF_SRC=.cpp
CFLAGS+= -g -fPIC -DTVU_LINUX -I$(PRJ_PATH)/include
LDFLAGS+= -L$(PRJ_PATH)/lib -lshmmediawrap -pthread -lrt

TEST_SRCS=$(wildcard $(SRC_PATH)/*$(SUF_SRC))
TEST_OBJS=$(patsubst %$(SUF_SRC), %.o, $(TEST_SRCS))
TEST_EXE=test_data_pro

all:$(TEST_EXE)
	@#echo $(TEST_OBJS)

$(TEST_OBJS):%.o:%$(SUF_SRC)
	$(CXX) -o $@ $(CFLAGS) -c $^

$(TEST_EXE):$(TEST_OBJS) $(LIB_AR_PRJ)
	$(CXX) -o $@ $< $(LDFLAGS)

clean:
	$(RM) $(TEST_OBJS) $(TEST_EXE)

install:
	@
uninstall:
	@

.PHONY:all clean install uninstall

